// <auto-generated />
namespace Infrastructor.MainBoundedContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Category_Upgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_Upgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201407300814489_Category_Upgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
